### ISSUE TITLE
fix failing integration tests (on travis and circleci)

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/DigitalOceanApp#106]

**Comment by championswimmer** [comment]
circle ci config has to be changed to Circle CI 2.0 for it to work on Circle CI

`.circleci/config.yml` type

https://circleci.com/docs/2.0/

**Comment by aggarwalpulkit596** [comment]
okay @championswimmer

**Comment by championswimmer** [comment]
if both are fixed and circle ci 2.0 also works, I'll make this 3000, else this is 2000 only if only travis works

**Comment by gupta1anubhav** [comment]
@championswimmer  can i work on this issue?

**Comment by aggarwalpulkit596** [comment]
@championswimmer travis has been fixed 👍 i have claimed for 3000 points can you make that 2000 while accepting 👍

**Comment by championswimmer** [comment]
if circleci works too, I'll allocate 3000, or else I'll give 2000 :)

**Comment by championswimmer** [comment]
since most of the work was done before deadline, you can continue to finish this PR

**Comment by abishekvashok** [comment]
Is this fixed @championswimmer?

**Comment by aggarwalpulkit596** [comment]
@abishekvashok Yup this has been fixed

**Comment by aggarwalpulkit596** [comment]
@abishekvashok will close it
