### ISSUE TITLE
Click not working on recyclerview while creating droplet

### ISSUE THREAD

**Issue by ronaksakhuja** [coding-blocks/DigitalOceanApp#11]
Click function of recyclerview not being called. @championswimmer  may i work on this?

**Comment by championswimmer** [comment]
Should probably add the click listener on the an inner view items, not on the recyclerview items

**Comment by ronaksakhuja** [comment]
I raised the issue, I'll work on it @thegeekybaniya :P

**Comment by ronaksakhuja** [comment]
I have made a pull request please check @championswimmer #20

**Comment by mkmar01** [comment]
@ronaksakhuja the solution by you provides the selection of multiple items in the recycler view and moreover, once the item is clicked then it disappears from the recycler view.
Therefore @championswimmer I would like to work on this issue. 
![ezgif com-video-to-gif-3](https://cloud.githubusercontent.com/assets/16780496/26284581/7359229c-3e5c-11e7-8699-c5b8bbfe11e2.gif)
