### ISSUE TITLE
Revamp the UX/UI of the DropletCreateActivity

### ISSUE THREAD

**Issue by jddeep** [coding-blocks/DigitalOceanApp#111]
Revamp the UX/UI of the DropletCreateActivity
**Original**
![Screenshot_20190523-202233](https://user-images.githubusercontent.com/43133646/58262960-d8f5d000-7d98-11e9-8d52-6dcfb3c5b09a.png)
**Revamped**
![Screenshot_20190526-185056](https://user-images.githubusercontent.com/43133646/58382407-64fd3700-7fe7-11e9-88c7-844bfd869384.png)

**Comment by jddeep** [comment]
@championswimmer @aggarwalpulkit596 @abhishek97 Please add BOSS bounty labels to this.

**Comment by aggarwalpulkit596** [comment]
Improvise the design a little bit more
With Proper Paddings, Margins and use rounded corner for cards

**Comment by naman653** [comment]
I would like to work on this issue if it's available.
