### ISSUE TITLE
Fix Travis builds

### ISSUE THREAD

**Issue by jddeep** [coding-blocks/DigitalOceanApp#115]
Remove Emulator checks in Travis builds.

This causes build failures currently.

**Comment by jddeep** [comment]
@aggarwalpulkit596 Please add BOSS bounty labels to this. I will be fixing this. Thanks.

**Comment by aggarwalpulkit596** [comment]
You have to fix the Travis instead of just removing from the travis there's no point of CI if instrumentation are not being done in that
