### ISSUE TITLE
All the regions are hardcoded

### ISSUE THREAD

**Issue by ashu10832** [coding-blocks/DigitalOceanApp#24]
#### Regions or Data Centres are hardcoded 
<img width="484" alt="screen shot 2017-05-24 at 1 56 16 pm" src="https://cloud.githubusercontent.com/assets/19621727/26393879/cd1bf6f0-4088-11e7-80ef-39492c59379e.png">

**How it should work:** They need to come from the Digital Ocean API. New Droplets cannot be created till this is done.

**Are you willing to work on this:** YES!

**Comment by championswimmer** [comment]
@ashu10832 you can work on this one
