### ISSUE TITLE
Complete the implementation of the droplet create process

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/DigitalOceanApp#3]

**Comment by singhalok641** [comment]
Can we have a description of what all needs to be done ?

**Comment by panwarab** [comment]
@championswimmer I had referenced this issue mistakenly, I was doing a few fixes for Travis and while numbering my commit, I mistakenly referenced this issue. My commit does not address the given problem statement.

**Comment by ashu10832** [comment]
I want to work on this issue
Please assign it to me.

**Comment by ronaksakhuja** [comment]
@championswimmer Please provide description of this issue.
