### ISSUE TITLE
Merge dandroidlib with the app

### ISSUE THREAD

**Issue by abishekvashok** [coding-blocks/DigitalOceanApp#40]
Currently the files from `doandroidlib` (along with the build.gradle files) resides in the `doandroidlib` folder.
For convenience and better standards can we merge them? i.e, put the files in the `doandroidlib` to be contained in the `app/src/main/java/in/tosc/digitaloceanapp/` folder where the other java files belonging to the app reside.

Thoughts?

**Comment by championswimmer** [comment]
The whole point of it is to make a library.
