### ISSUE TITLE
Add an apk branch which is automatically updated by latest app builds

### ISSUE THREAD

**Issue by abishekvashok** [coding-blocks/DigitalOceanApp#41]
For better testing and usabliltiy can we have an apk branch where the latest (or manually decied number of latest) `.apk` file(s) reside.

The apk files will be pushed by Travis CI on each successful build in the `master` branch.

thoughts? Can we have it?

**Comment by championswimmer** [comment]
We'll do it via Github releases. Why pollute git branches and histories

**Comment by abishekvashok** [comment]
Then can have a script to auto release after each commit @championswimmer? What are your thoughts?

**Comment by championswimmer** [comment]
Travis can do that on tags
