### ISSUE TITLE
Signup is not working in App.

### ISSUE THREAD

**Issue by ArushiSinghal** [coding-blocks/DigitalOceanApp#53]
![screenshot_2017-06-25-17-44-38](https://user-images.githubusercontent.com/20858804/27694342-7018f0dc-5d09-11e7-96f9-d7215a8d992d.png)

**Comment by championswimmer** [comment]
this should basically just redirect to signup page in chrome custom tab.

**Comment by sarabjeetoberoi** [comment]
this should basically just redirect to signup page in chrome custom tab.

**Comment by ojasvajain** [comment]
Please review [PR](https://github.com/coding-blocks/DigitalOceanApp/pull/60)
