### ISSUE TITLE
improve code coverage to > 50%

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/DigitalOceanApp#59]

**Comment by Pritom14** [comment]
I would like to work on this issue

**Comment by aggarwalpulkit596** [comment]
Working on it

**Comment by aggarwalpulkit596** [comment]
issue fixed in https://github.com/coding-blocks/DigitalOceanApp/pull/79

**Comment by aggarwalpulkit596** [comment]
issue can be closed now fixed and merged in #80
