### ISSUE TITLE
Add databinding in activities

### ISSUE THREAD

**Issue by AkshayCHD** [coding-blocks/DigitalOceanApp#72]
Parent Issue #65

**Comment by aggarwalpulkit596** [comment]
@championswimmer  bhaiya is this issue still open?

**Comment by 4lch4** [comment]
@aggarwalpulkit596 it appears there was a fix in @AkshayCHD's commit referenced above but there's a conflict issue between some files.

**Comment by aggarwalpulkit596** [comment]
@Alcha  that means i'm still able to make a pr for this issue right ?

**Comment by 4lch4** [comment]
Don't see why not. As long as you can get a working PR together before @AkshayCHD, then sure?

**Comment by aggarwalpulkit596** [comment]
@Alcha Issue fixed in pull request #86

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya  kindly review this pr

**Comment by jddeep** [comment]
Is this issue open for BOSS 2019? Can I work on this? @championswimmer @the-dagger

**Comment by jddeep** [comment]
I will be working on this @abhishek97

**Comment by aggarwalpulkit596** [comment]
Closed via #98

**Comment by jddeep** [comment]
> Closed via #98

@aggarwalpulkit596 Why is this closed? @abhishek97 said that I can work on this.

**Comment by aggarwalpulkit596** [comment]
@jddeep it was already resolved you can work on CBOnlineApp instead you can add data binding there too
